worker_processes auto;
rtmp_auto_push on;
events {}

rtmp {
    server {
        listen 1935; # Porta padrão RTMP
        chunk_size 4096;

        # 'live' é o nome da nossa aplicação de streaming
        application live {
            live on;      # Habilita a transmissão ao vivo
            record off;   # Não salva o arquivo no disco (por enquanto)
            on_publish http://api-backend:5000/on_publish;
            on_publish_done http://api-backend:5000/on_publish_done;
        }
    }
}